root: true
env:
  jest: true
  node: true
globals:
  Promise: readonly
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
  project: ./tsconfig.eslint.json
plugins:
  - "@typescript-eslint"
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
